#!/usr/bin/env bash
# Config check + load.
#
# Each demo passes its own config.yaml path. Source this file,
# then call `load_config <path/to/config.yaml>`; it exports CLUSTER_NAME,
# API_PORT, HTTP_PORT, CROSSPLANE_NAMESPACE, MIN_CRDS, and SETUP_DIR into the
# current shell.
#
# Source this file; do not execute it.

# Resolve this script's directory so we can find load_config.py regardless of cwd.
_LOAD_CONFIG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Fallbacks so this works whether or not common.sh is already sourced.
if ! command -v print_success >/dev/null 2>&1; then
    print_success() { echo "✓ $1"; }
    print_error()   { echo "✗ $1" >&2; }
fi

# load_config <config_file> — verify the config exists, parse it, write the
# resulting exports to a .env.sh next to the config (replacing any existing one),
# then source it into the current shell. Returns non-zero on any failure.
load_config() {
    local config_file="${1:-config.yaml}"

    # Config check.
    if [ ! -f "$config_file" ]; then
        print_error "config.yaml NOT found: $config_file"
        return 1
    fi
    print_success "config.yaml found: $config_file"

    # Load configuration. The python helper prints `export` lines on stdout and a
    # summary on stderr.
    local exports
    if ! exports="$(python3 "$_LOAD_CONFIG_DIR/load_config.py" "$config_file")"; then
        print_error "Failed to load configuration from $config_file"
        return 1
    fi

    # Write (replacing any existing) .env.sh alongside the config, then source
    # it. .env.sh lives in the demo folder and is gitignored (.env.*).
    local env_file
    env_file="$(dirname "$config_file")/.env.sh"
    {
        printf '# Generated by load_config from %s — do not edit (regenerated each run).\n' "$config_file"
        printf '%s\n' "$exports"
    } > "$env_file"
    print_success "wrote $env_file"
    # shellcheck source=/dev/null
    source "$env_file"
}
